# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b5f1f1535ef83e9573612442d998c26e"
name = "mockey"
handle = "mockey"
application_url = "https://european-hard-emma-geographical.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-86b0cc45.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://european-hard-emma-geographical.trycloudflare.com/auth/callback",
  "https://european-hard-emma-geographical.trycloudflare.com/auth/shopify/callback",
  "https://european-hard-emma-geographical.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
